# Generated by Django 3.2.9 on 2021-11-05 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ubereats', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Platform',
        ),
    ]
