# Generated by Django 3.2.9 on 2021-11-05 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ubereats', '0002_delete_platform'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='completed',
            new_name='is_completed',
        ),
        migrations.AddField(
            model_name='order',
            name='drink',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='飲料'),
        ),
        migrations.AlterField(
            model_name='order',
            name='food',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='食物'),
        ),
    ]
