# Generated by Django 3.2.9 on 2021-11-05 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ubereats', '0003_auto_20211105_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='drink',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='飲料'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='name',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='司機'),
        ),
        migrations.AlterField(
            model_name='store',
            name='food',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='食物'),
        ),
        migrations.AlterField(
            model_name='store',
            name='name',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='店家'),
        ),
    ]
